# fly.toml app configuration file generated for peppe-forneria on 2024-06-11T18:11:32-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'peppe-forneria'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '16gb'
  cpu_kind = 'performance'
  cpus = 8

[env]
  PORT = "3000"
  NODE_ENV = "prod"

  MYSQL_PORT = "3306"
  MYSQL_DATABASE = "pizza_orders"
  MYSQL_USER = "admin"
  MYSQL_HOST = "peppe-forneria-db.cq68vpthk5mu.us-east-1.rds.amazonaws.com"
  MYSQL_PASS = "peppeforneriadbpass"
  MYSQL_TIMEZONE = "-03:00"

  DB_LOGGING = "false"

  ENCRYPTION_KEY = "FYgiZwXtVGmMbJ6TQAFuyyf2iJmmKnkU"
  ENCRYPTION_IV = "rHGKUpGCuvqSPeCK"

  JWT_EXP_IN_MINUTES = "1440"
  JWT_SECRET = "tBew2E7BRYCbdQTg4y2BJmfFiZgJjuLUZR4VSFv6jpEC5pD7c5"

